// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/User/Desktop/lab/avito-shop/internal/repository/merchRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "avito-shop/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMerchRepository is a mock of MerchRepository interface.
type MockMerchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchRepositoryMockRecorder
}

// MockMerchRepositoryMockRecorder is the mock recorder for MockMerchRepository.
type MockMerchRepositoryMockRecorder struct {
	mock *MockMerchRepository
}

// NewMockMerchRepository creates a new mock instance.
func NewMockMerchRepository(ctrl *gomock.Controller) *MockMerchRepository {
	mock := &MockMerchRepository{ctrl: ctrl}
	mock.recorder = &MockMerchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchRepository) EXPECT() *MockMerchRepositoryMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockMerchRepository) GetByName(merchName string) (*model.MerchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", merchName)
	ret0, _ := ret[0].(*model.MerchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockMerchRepositoryMockRecorder) GetByName(merchName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockMerchRepository)(nil).GetByName), merchName)
}
