// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/User/Desktop/lab/avito-shop/internal/repository/transactionRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "avito-shop/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionRepository) Create(transaction *model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionRepositoryMockRecorder) Create(transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepository)(nil).Create), transaction)
}

// GetAllReceivedByUserName mocks base method.
func (m *MockTransactionRepository) GetAllReceivedByUserName(userName string) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllReceivedByUserName", userName)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllReceivedByUserName indicates an expected call of GetAllReceivedByUserName.
func (mr *MockTransactionRepositoryMockRecorder) GetAllReceivedByUserName(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllReceivedByUserName", reflect.TypeOf((*MockTransactionRepository)(nil).GetAllReceivedByUserName), userName)
}

// GetAllSentByUserName mocks base method.
func (m *MockTransactionRepository) GetAllSentByUserName(userName string) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSentByUserName", userName)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSentByUserName indicates an expected call of GetAllSentByUserName.
func (mr *MockTransactionRepositoryMockRecorder) GetAllSentByUserName(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSentByUserName", reflect.TypeOf((*MockTransactionRepository)(nil).GetAllSentByUserName), userName)
}
