version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8081:8081"
    environment:
      # енвы подключения к БД
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=shop
      - DATABASE_HOST=db
      # порт сервиса
      - SERVER_PORT=8081
      # JWT секретный ключ
      - JWT_SECRET_KEY=dK8Lp#9$mN2^vF4@jH5*qW7&xR3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - test-network
networks:
  test-network: